# write your docker-compose code here.Use the `docker compose` command instead of the legacy `docker-compose`, as it is integrated into Docker CLI (v20.10+),eliminating the need for a separate binary. It provides better performance, consistency, and is actively maintained, unlike the legacy command.
services:
  todo-application:
    image: todo-application-image:latest
    container_name: todo-application-1
    ports:
      - "8082:8081"
    depends_on:
      - mysql-db-1
    networks:
      - todo-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db-1
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: tododb
    ports: 
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network
volumes:
  mysql-data:

networks:
  todo-network:
    driver: bridge  